### PR TITLE
Don't default index url to public pypi. Defer to underlying libs

### PR DESCRIPTION
**Pull request by analogue**
Testing done: `tox -e upgrade-requirements' now works with serviecs/ad_realtime_bidding

Internal ticket: CORESERV-10904

### CODE REVIEW

**Review by ymilki — APPROVED** [review]
lgtm. We want to rely on the normal expected defaults for pypi.

**Review by asottile — CHANGES_REQUESTED** [review]
please don't change this -- it breaks my uses of this

the service in question should be fixed instead to utilize the `--index-url` argument explicitly

**Comment by analogue** [comment]
> please don't change this -- it breaks my uses of this
> 
> the service in question should be fixed instead to utilize the `--index-url` argument explicitly

We'd like the default to be picked up from `/etc/pip.conf` which I believe is the default for the rest python / pip related tools.  Having `upgrade-requirements` as the the outlier is desirable.

**Comment by asottile** [comment]
A better solution would be to remove the argument entirely and release 2.0.0

please don't merge with unresolved reviews

**Pull request merged**
