### PR TITLE
Use env var to ignore unpinned requirements

### PR DESCRIPTION
**Pull request by vkhromov**
Ignore unpinned requirements listed in
`CHECK_REQUIREMENTS_IGNORE_UNPINNED` environment variable.

### CODE REVIEW

**Comment by asottile** [comment]
No, this goes against the explicit goals of the tool. If your don't want to pin, don't use check-requirements. Plus you can already deselect that test using -k if you vreallly wanted

**Comment by vkhromov** [comment]
> No, this goes against the explicit goals of the tool. If your don't want to pin, don't use check-requirements. Plus you can already deselect that test using -k if you vreallly wanted

We need `-e git+git://github.com/benoitc/http-parser.git@2306df28fbd7946036a2609776a77833f5dda81e#egg=http-parser` since none of released versions support Python 3.7, could you please provide a working `-k` option for that?

**Comment by asottile** [comment]
git urls can't be traced so that are also intentionally disallowed. I think the process at yelp (unless it has changed) is to release a .post1 version to internal pypi and use that?

Though if it is this late and http-parser hasn't made a release might be a good sign to move to something else

**Comment by vkhromov** [comment]
> git urls can't be traced so that are also intentionally disallowed. I think the process at yelp (unless it has changed) is to release a .post1 version to internal pypi and use that?
> 
> Though if it is this late and http-parser hasn't made a release might be a good sign to move to something else

Posting .post1 version to internal repo isn't enough, PaaSTA should be built from the external pypi repo as well.

We could migrate from http-parser to something else, but we definitely not going to do that in the any foreseeable future, as that requires some non-trivial effort of either changing pymesos or migrating to some other library.

**Comment by asottile** [comment]
> > git urls can't be traced so that are also intentionally disallowed. I think the process at yelp (unless it has changed) is to release a .post1 version to internal pypi and use that?
> > Though if it is this late and http-parser hasn't made a release might be a good sign to move to something else
> 
> Posting .post1 version to internal repo isn't enough, PaaSTA should be built from the external pypi repo as well.
> 
> We could migrate from http-parser to something else, but we definitely not going to do that in the any foreseeable future, as that requires some non-trivial effort of either changing pymesos or migrating to some other library.

I thought there were public and private requirements files in paasta already? 

Either way, you should change paasta and not put back doors in tools, one way to do so would be to split out the unpinned / untracked requirements to a separate file and install from all files

**Comment by vkhromov** [comment]
> > > git urls can't be traced so that are also intentionally disallowed. I think the process at yelp (unless it has changed) is to release a .post1 version to internal pypi and use that?
> > > Though if it is this late and http-parser hasn't made a release might be a good sign to move to something else
> > 
> > 
> > Posting .post1 version to internal repo isn't enough, PaaSTA should be built from the external pypi repo as well.
> > We could migrate from http-parser to something else, but we definitely not going to do that in the any foreseeable future, as that requires some non-trivial effort of either changing pymesos or migrating to some other library.
> 
> I thought there were public and private requirements files in paasta already?
> 
> Either way, you should change paasta and not put back doors in tools, one way to do so would be to split out the unpinned / untracked requirements to a separate file and install from all files

So, let me double check that I got your suggestion right.
Are you suggesting to create a custom build of `http-parser` (`http-parser-yelp`?), a custom build of `pymesos` (`pymesos-yelp`?) which depends on `http-parser-yelp`, put them into both of Yelp internal and external pypi repos, and then use `pymesos-yelp` instead of `pymesos` as a dependency for PaaSTA?

**Comment by asottile** [comment]
> > > > git urls can't be traced so that are also intentionally disallowed. I think the process at yelp (unless it has changed) is to release a .post1 version to internal pypi and use that?
> > > > Though if it is this late and http-parser hasn't made a release might be a good sign to move to something else
> > > 
> > > 
> > > Posting .post1 version to internal repo isn't enough, PaaSTA should be built from the external pypi repo as well.
> > > We could migrate from http-parser to something else, but we definitely not going to do that in the any foreseeable future, as that requires some non-trivial effort of either changing pymesos or migrating to some other library.
> > 
> > 
> > I thought there were public and private requirements files in paasta already?
> > Either way, you should change paasta and not put back doors in tools, one way to do so would be to split out the unpinned / untracked requirements to a separate file and install from all files
> 
> So, let me double check that I got your suggestion right.
> Are you suggesting to create a custom build of `http-parser` (`http-parser-yelp`?), a custom build of `pymesos` (`pymesos-yelp`?) which depends on `http-parser-yelp`, put them into both of Yelp internal and external pypi repos, and then use `pymesos-yelp` instead of `pymesos` as a dependency for PaaSTA?

No but that would be another solution

I'm suggesting a `requirements-unchecked.txt` in paasta where you sequester the workaround unpinned packages

**Comment by solarkennedy** [comment]
@vkhromov it has been a year on this. What do you think about @asottile 's last suggestion to have another requirements file that is unchecked?

**Comment by vkhromov** [comment]
Just a bit of context.
Originally we needed this PR because `pymesos` used a quite old version of `http-parser` which was incompatible with Python >=3.7.
Since then, `http-parser` was updated and is compatible with recent Python versions, so we don't need a workaround for `http-parser` anymore.
Also the solution suggested by @asottile works and is better than solution in this PR, but again we don't need that anymore.

**Pull request closed without merging**
